site_name: Портфолио ТЗ
site_url: https://<твое_имя_пользователя>.github.io/portfolio-tz/
theme:
  name: material
nav:
  - Главная: index.md
  - Общие сведения: 02_Общие_сведения.md
  - Глоссарий: 03_Глоссарий.md
  - Диаграммы: 04_Диаграммы.md
  - Функциональные требования:
      - Основное: 05_Функциональные.md
      - Регистрация: 05.1_Регистрация.md
      - Личный кабинет: 05.2_Личный_кабинет.md
      - Поиск и фильтры: 05.3_Поиск_и_фильтры.md
  - Нефункциональные требования: 06_Нефункциональные.md
  - Архитектура: 07_Архитектура.md
  - Интеграции:
      - Обзор раздела: 08_Интеграции.md
      - API Обзор: 08.1_API_Обзор.md
      - API Методы: 08.2_API_Методы.md
  - UI/UX: 09_UI_UX.md
  - Тестирование: 10_Тестирование.md
  - Управление требованиями: 11_Управление.md
  - Приложения: 12_Приложения.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
plugins:
  - search
